create about-us section
0kri/additional-team-homework pull request #1
Opened 2023-01-05 09:09 UTC by shakomentol

2023-01-06 09:27 UTC, 0kri commented on style.css
> +div {
ასე რომ სტილავ სხვა დივები არაუშავს? 👎

2023-01-06 09:31 UTC, 0kri requested changes
დაგიწერე ყველა ლაინზე სად უნდა დაკლასო და მერე დავმერჯოთ

2023-01-06 09:31 UTC, 0kri commented on style.css
> +p {
aqac igive, clasebi mieci

2023-01-06 09:31 UTC, 0kri commented on style.css
> +h3 {
esec daklase da egaa mere davmergot

2023-01-07 09:18 UTC, shakomentol commented on style.css
> +div {
გავასწორე აბა ნახეე მძინარაა

2023-01-07 09:18 UTC, shakomentol commented on style.css
> +p {
გელოდებიიი

2023-01-07 09:18 UTC, shakomentol commented on style.css
> +h3 {
დავკლასეეე სიუუ

2023-01-07 10:13 UTC, 0kri approved these changes
conflicts ressolved good job

2023-01-07 10:13 UTC, merged